name: Shrine
description: Learn how to use Material for structure and layout.

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1
  cloud_firestore: ^0.9.5+2
  cloud_functions: ^0.1.1+1
  firebase_auth: ^0.8.1+4
  firebase_messaging: ^4.0.0+1
  intl: ^0.15.6
  firebase_admob: ^0.8.0+3
  flutter_launcher_icons: ^0.7.0
  cupertino_icons: ^0.1.0
  http: ^0.12.0+1
  qr_flutter: ^2.0.0+51
  qrcode_reader: ^0.4.4
  btnonce:
    path: ../plugins/btnonce
  fbfunctions:
    path: ../plugins/fbfunctions


  flutter_firebase_ui:
      path: flutter_firebase_ui

flutter_icons:
  image_path: "assets/icon/ic_launcher_foreground.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: Rubik
        fonts:
          - asset: fonts/Rubik-Regular.ttf
          - asset: fonts/Rubik-Medium.ttf
            weight: 500
  uses-material-design: true
  assets:
    - assets/main_backdrop.png
    - assets/subscribe_backdrop.png
    - assets/data/item_int2string.json
    - assets/ic_launcher_foreground.png
    - assets/diamond.png
    - assets/item_1.png
    - assets/item_2.png
    - assets/item_3.png
    - assets/item_4.png
    - assets/item_5.png
    - assets/item_6.png
    - assets/item_7.png
    - assets/item_8.png
    - assets/item_9.png
    - assets/item_10.png
    - assets/item_11.png
    - assets/item_12.png
    - assets/item_13.png
    - assets/item_14.png
    - assets/item_15.png
    - assets/item_16.png
    - assets/item_17.png
    - assets/item_18.png
    - assets/item_19.png
    - assets/item_20.png
    - assets/item_21.png
    - assets/item_22.png
    - assets/item_23.png
    - assets/item_24.png
    - assets/item_25.png
    - assets/item_26.png
    - assets/item_27.png
    - assets/item_28.png
    - assets/item_29.png
    - assets/item_30.png
    - assets/item_31.png
    - assets/item_32.png
    - assets/item_33.png
    - assets/item_34.png
    - assets/item_35.png
    - assets/item_36.png
    - assets/item_37.png
    - assets/item_38.png
    - assets/item_39.png
    - assets/item_40.png
    - assets/item_41.png
    - assets/item_42.png
    - assets/item_43.png
    - assets/item_44.png
    - assets/item_45.png
    - assets/item_46.png
    - assets/item_47.png
    - assets/item_48.png
    - assets/item_49.png
    - assets/item_50.png
    - assets/item_51.png
    - assets/item_52.png
    - assets/item_53.png
    - assets/item_54.png
    - assets/item_55.png
    - assets/item_56.png
    - assets/item_57.png
    - assets/item_58.png
    - assets/item_59.png
    - assets/item_60.png
    - assets/item_61.png
    - assets/item_62.png
    - assets/item_63.png
    - assets/item_64.png
    - assets/item_65.png
    - assets/item_66.png
    - assets/item_67.png
    - assets/item_68.png
    - assets/item_69.png
    - assets/item_70.png
    - assets/item_71.png
    - assets/item_72.png
    - assets/item_73.png
    - assets/item_74.png
    - assets/item_75.png
    - assets/item_76.png
    - assets/item_77.png
    - assets/item_78.png
    - assets/item_79.png
    - assets/item_80.png
    - assets/item_81.png
    - assets/item_82.png
    - assets/item_83.png
    - assets/item_84.png
    - assets/item_85.png
    - assets/item_86.png
    - assets/item_87.png
    - assets/item_88.png
    - assets/item_89.png
    - assets/item_90.png
    - assets/item_91.png
    - assets/item_92.png
    - assets/item_93.png
    - assets/item_94.png
    - assets/item_95.png
    - assets/item_96.png
    - assets/item_97.png
    - assets/item_98.png
    - assets/item_99.png
    - assets/item_100.png
    - assets/item_101.png
    - assets/item_102.png
    - assets/item_103.png
    - assets/item_104.png
    - assets/item_105.png
    - assets/item_106.png
    - assets/item_107.png
    - assets/item_108.png
    - assets/item_109.png
    - assets/item_110.png
    - assets/item_111.png
    - assets/item_112.png
    - assets/item_113.png
    - assets/item_114.png
    - assets/item_115.png
    - assets/item_116.png
    - assets/item_117.png
    - assets/item_118.png
    - assets/item_119.png
    - assets/item_120.png
    - assets/item_121.png
    - assets/item_122.png
    - assets/item_123.png
    - assets/item_124.png
    - assets/item_125.png
    - assets/item_126.png
    - assets/item_127.png
    - assets/item_128.png
    - assets/item_129.png
    - assets/item_130.png
    - assets/item_131.png
    - assets/item_132.png
    - assets/item_133.png
    - assets/item_134.png
    - assets/item_135.png
    - assets/item_136.png
    - assets/item_137.png
    - assets/item_138.png
    - assets/item_139.png
    - assets/item_140.png
    - assets/item_141.png
    - assets/item_142.png
    - assets/item_143.png
    - assets/item_144.png
    - assets/item_145.png
    - assets/item_146.png
    - assets/item_147.png
    - assets/item_148.png
    - assets/item_149.png
    - assets/item_150.png
    - assets/item_151.png
    - assets/item_152.png
    - assets/item_153.png
    - assets/item_154.png
    - assets/item_155.png
    - assets/item_156.png
    - assets/item_157.png
    - assets/item_158.png
    - assets/item_159.png
    - assets/item_160.png
    - assets/item_161.png
    - assets/item_162.png
    - assets/item_163.png
    - assets/item_164.png
    - assets/item_165.png
    - assets/item_166.png
    - assets/item_167.png
    - assets/item_168.png
    - assets/item_169.png
    - assets/item_170.png
    - assets/item_171.png
    - assets/item_172.png
    - assets/item_173.png
    - assets/item_174.png
    - assets/item_175.png
    - assets/item_176.png
    - assets/item_177.png
    - assets/item_178.png
    - assets/item_179.png
    - assets/item_180.png
    - assets/item_181.png
    - assets/item_182.png
    - assets/item_183.png
    - assets/item_184.png
    - assets/item_185.png
    - assets/item_186.png
    - assets/item_187.png
    - assets/item_188.png
    - assets/item_189.png
    - assets/item_190.png
    - assets/item_191.png
    - assets/item_192.png
    - assets/item_193.png
    - assets/item_194.png
    - assets/item_195.png
    - assets/item_196.png
    - assets/item_197.png
    - assets/item_198.png
    - assets/item_199.png
    - assets/item_200.png
    - assets/item_201.png
