name: LeagueIQ
description: Pure awesomesauce

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1
  cloud_firestore: ^0.9.5+2
  cloud_functions: ^0.1.1+1
  firebase_auth: ^0.8.1+4
  firebase_messaging: ^4.0.0+1
  intl: ^0.15.6
  firebase_admob: ^0.8.0+3
  flutter_launcher_icons: ^0.7.0
  cupertino_icons: ^0.1.0
  http: ^0.12.0+1
  qr_flutter: ^2.0.0+51
  qrcode_reader: ^0.4.4
  btnonce:
    path: ../plugins/btnonce
  fbfunctions:
    path: ../plugins/fbfunctions
  launchbrowser:
    path: ../plugins/launchbrowser


  flutter_firebase_ui:
      path: flutter_firebase_ui

flutter_icons:
  image_path: "assets/icon/ic_launcher_foreground.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: Rubik
        fonts:
          - asset: assets/fonts/Rubik-Regular.ttf
          - asset: assets/fonts/Rubik-Medium.ttf
            weight: 500
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 300
          - asset: assets/fonts/Roboto-Black.ttf
            weight: 600
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Light.ttf
            weight: 200
          - asset: assets/fonts/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Rubik-Medium.ttf
            weight: 400

  uses-material-design: true
  assets:
    #json
    - assets/data/item2id.json

    #imgs
    - assets/imgs/lol1.png
    - assets/imgs/lol2.png
    - assets/imgs/lol3.png
    - assets/imgs/lol4.png
    - assets/imgs/lol5.png
    - assets/ic_launcher_foreground.png
#item imgs
    - assets/items/unknown.png
    - assets/items/4403.png
    - assets/items/4402.png
    - assets/items/4401.png
    - assets/items/4302.png
    - assets/items/4301.png
    - assets/items/4204.png
    - assets/items/4203.png
    - assets/items/4202.png
    - assets/items/4201.png
    - assets/items/4105.png
    - assets/items/4104.png
    - assets/items/4103.png
    - assets/items/4102.png
    - assets/items/4101.png
    - assets/items/4004.png
    - assets/items/4003.png
    - assets/items/4001.png
    - assets/items/3916.png
    - assets/items/3907.png
    - assets/items/3905.png
    - assets/items/3903.png
    - assets/items/3902.png
    - assets/items/3901.png
    - assets/items/3814.png
    - assets/items/3813.png
    - assets/items/3812.png
    - assets/items/3802.png
    - assets/items/3801.png
    - assets/items/3800.png
    - assets/items/3751.png
    - assets/items/3748.png
    - assets/items/3742.png
    - assets/items/3715.png
    - assets/items/3706.png
    - assets/items/3695.png
    - assets/items/3694.png
    - assets/items/3693.png
    - assets/items/3692.png
    - assets/items/3691.png
    - assets/items/3690.png
    - assets/items/3683.png
    - assets/items/3682.png
    - assets/items/3681.png
    - assets/items/3680.png
    - assets/items/3675.png
    - assets/items/3673.png
    - assets/items/3672.png
    - assets/items/3671.png
    - assets/items/3649.png
    - assets/items/3648.png
    - assets/items/3647.png
    - assets/items/3645.png
    - assets/items/3643.png
    - assets/items/3642.png
    - assets/items/3641.png
    - assets/items/3640.png
    - assets/items/3637.png
    - assets/items/3636.png
    - assets/items/3635.png
    - assets/items/3634.png
    - assets/items/3633.png
    - assets/items/3631.png
    - assets/items/3630.png
    - assets/items/3600.png
    - assets/items/3599.png
    - assets/items/3520.png
    - assets/items/3514.png
    - assets/items/3513.png
    - assets/items/3512.png
    - assets/items/3508.png
    - assets/items/3504.png
    - assets/items/3462.png
    - assets/items/3461.png
    - assets/items/3460.png
    - assets/items/3455.png
    - assets/items/3422.png
    - assets/items/3416.png
    - assets/items/3410.png
    - assets/items/3401.png
    - assets/items/3400.png
    - assets/items/3390.png
    - assets/items/3389.png
    - assets/items/3388.png
    - assets/items/3387.png
    - assets/items/3386.png
    - assets/items/3385.png
    - assets/items/3384.png
    - assets/items/3383.png
    - assets/items/3382.png
    - assets/items/3380.png
    - assets/items/3379.png
    - assets/items/3374.png
    - assets/items/3373.png
    - assets/items/3371.png
    - assets/items/3364.png
    - assets/items/3363.png
    - assets/items/3362.png
    - assets/items/3361.png
    - assets/items/3348.png
    - assets/items/3345.png
    - assets/items/3340.png
    - assets/items/3312.png
    - assets/items/3311.png
    - assets/items/3310.png
    - assets/items/3309.png
    - assets/items/3308.png
    - assets/items/3307.png
    - assets/items/3306.png
    - assets/items/3305.png
    - assets/items/3304.png
    - assets/items/3303.png
    - assets/items/3302.png
    - assets/items/3301.png
    - assets/items/3285.png
    - assets/items/3231.png
    - assets/items/3230.png
    - assets/items/3222.png
    - assets/items/3211.png
    - assets/items/3200.png
    - assets/items/3198.png
    - assets/items/3197.png
    - assets/items/3196.png
    - assets/items/3194.png
    - assets/items/3193.png
    - assets/items/3191.png
    - assets/items/3190.png
    - assets/items/3187.png
    - assets/items/3185.png
    - assets/items/3184.png
    - assets/items/3181.png
    - assets/items/3175.png
    - assets/items/3174.png
    - assets/items/3173.png
    - assets/items/3172.png
    - assets/items/3170.png
    - assets/items/3165.png
    - assets/items/3163.png
    - assets/items/3162.png
    - assets/items/3161.png
    - assets/items/3158.png
    - assets/items/3157.png
    - assets/items/3156.png
    - assets/items/3155.png
    - assets/items/3153.png
    - assets/items/3152.png
    - assets/items/3151.png
    - assets/items/3149.png
    - assets/items/3148.png
    - assets/items/3147.png
    - assets/items/3146.png
    - assets/items/3145.png
    - assets/items/3144.png
    - assets/items/3143.png
    - assets/items/3142.png
    - assets/items/3140.png
    - assets/items/3139.png
    - assets/items/3137.png
    - assets/items/3136.png
    - assets/items/3135.png
    - assets/items/3134.png
    - assets/items/3133.png
    - assets/items/3131.png
    - assets/items/3128.png
    - assets/items/3124.png
    - assets/items/3123.png
    - assets/items/3122.png
    - assets/items/3118.png
    - assets/items/3117.png
    - assets/items/3116.png
    - assets/items/3115.png
    - assets/items/3114.png
    - assets/items/3113.png
    - assets/items/3112.png
    - assets/items/3111.png
    - assets/items/3110.png
    - assets/items/3109.png
    - assets/items/3108.png
    - assets/items/3107.png
    - assets/items/3105.png
    - assets/items/3104.png
    - assets/items/3102.png
    - assets/items/3101.png
    - assets/items/3100.png
    - assets/items/3098.png
    - assets/items/3097.png
    - assets/items/3096.png
    - assets/items/3095.png
    - assets/items/3094.png
    - assets/items/3092.png
    - assets/items/3091.png
    - assets/items/3090.png
    - assets/items/3089.png
    - assets/items/3087.png
    - assets/items/3086.png
    - assets/items/3085.png
    - assets/items/3084.png
    - assets/items/3083.png
    - assets/items/3082.png
    - assets/items/3080.png
    - assets/items/3078.png
    - assets/items/3077.png
    - assets/items/3076.png
    - assets/items/3075.png
    - assets/items/3074.png
    - assets/items/3073.png
    - assets/items/3072.png
    - assets/items/3071.png
    - assets/items/3070.png
    - assets/items/3069.png
    - assets/items/3068.png
    - assets/items/3067.png
    - assets/items/3065.png
    - assets/items/3057.png
    - assets/items/3056.png
    - assets/items/3053.png
    - assets/items/3052.png
    - assets/items/3050.png
    - assets/items/3048.png
    - assets/items/3047.png
    - assets/items/3046.png
    - assets/items/3044.png
    - assets/items/3043.png
    - assets/items/3042.png
    - assets/items/3041.png
    - assets/items/3040.png
    - assets/items/3036.png
    - assets/items/3035.png
    - assets/items/3033.png
    - assets/items/3031.png
    - assets/items/3030.png
    - assets/items/3029.png
    - assets/items/3028.png
    - assets/items/3027.png
    - assets/items/3026.png
    - assets/items/3025.png
    - assets/items/3024.png
    - assets/items/3022.png
    - assets/items/3020.png
    - assets/items/3010.png
    - assets/items/3009.png
    - assets/items/3008.png
    - assets/items/3007.png
    - assets/items/3006.png
    - assets/items/3005.png
    - assets/items/3004.png
    - assets/items/3003.png
    - assets/items/3001.png
    - assets/items/2424.png
    - assets/items/2423.png
    - assets/items/2422.png
    - assets/items/2421.png
    - assets/items/2420.png
    - assets/items/2419.png
    - assets/items/2403.png
    - assets/items/2319.png
    - assets/items/2140.png
    - assets/items/2139.png
    - assets/items/2138.png
    - assets/items/2065.png
    - assets/items/2062.png
    - assets/items/2061.png
    - assets/items/2060.png
    - assets/items/2059.png
    - assets/items/2058.png
    - assets/items/2057.png
    - assets/items/2056.png
    - assets/items/2055.png
    - assets/items/2054.png
    - assets/items/2053.png
    - assets/items/2052.png
    - assets/items/2051.png
    - assets/items/2050.png
    - assets/items/2047.png
    - assets/items/2033.png
    - assets/items/2032.png
    - assets/items/2031.png
    - assets/items/2015.png
    - assets/items/2013.png
    - assets/items/2012.png
    - assets/items/2011.png
    - assets/items/2010.png
    - assets/items/2009.png
    - assets/items/2004.png
    - assets/items/2003.png
    - assets/items/1419.png
    - assets/items/1416.png
    - assets/items/1414.png
    - assets/items/1413.png
    - assets/items/1412.png
    - assets/items/1402.png
    - assets/items/1401.png
    - assets/items/1400.png
    - assets/items/1083.png
    - assets/items/1082.png
    - assets/items/1059.png
    - assets/items/1058.png
    - assets/items/1057.png
    - assets/items/1056.png
    - assets/items/1055.png
    - assets/items/1054.png
    - assets/items/1053.png
    - assets/items/1052.png
    - assets/items/1051.png
    - assets/items/1043.png
    - assets/items/1042.png
    - assets/items/1041.png
    - assets/items/1039.png
    - assets/items/1038.png
    - assets/items/1037.png
    - assets/items/1036.png
    - assets/items/1033.png
    - assets/items/1031.png
    - assets/items/1029.png
    - assets/items/1028.png
    - assets/items/1027.png
    - assets/items/1026.png
    - assets/items/1018.png
    - assets/items/1011.png
    - assets/items/1006.png
    - assets/items/1004.png
    - assets/items/1001.png