name: LeagueIQ
description: Pure awesomesauce

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.7.4-pre.77' 

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1
  cloud_firestore: ^0.9.5+2
  cloud_functions: ^0.1.1+1
  firebase_auth: ^0.8.1+4
  firebase_messaging: ^4.0.0+1
  intl: ^0.15.6
  firebase_admob: ^0.8.0+3
  flutter_launcher_icons: ^0.7.0
  cupertino_icons: ^0.1.0
  http: ^0.12.0+1
  qr_flutter: ^2.0.0+51
  qrcode_reader: ^0.4.4
  watcher: ^0.9.7+10
  btnonce:
    path: ./plugins/btnonce
  fbfunctions:
    path: ./plugins/fbfunctions
  launchbrowser:
    path: ./plugins/launchbrowser


  flutter_firebase_ui:
      path: flutter_firebase_ui

flutter_icons:
  image_path: "assets/icon/ic_launcher_foreground.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: Rubik
        fonts:
          - asset: assets/fonts/Rubik-Regular.ttf
          - asset: assets/fonts/Rubik-Medium.ttf
            weight: 500
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 300
          - asset: assets/fonts/Roboto-Black.ttf
            weight: 600
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Light.ttf
            weight: 200
          - asset: assets/fonts/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Rubik-Medium.ttf
            weight: 400

  uses-material-design: true
  assets:
    #json
    - assets/data/item2id.json

    #imgs
    - assets/imgs/1.png
    - assets/imgs/2.png
    - assets/imgs/3.png
    - assets/imgs/4.png
    - assets/logo.png
#item imgs
    - assets/item_imgs/0.png
    - assets/item_imgs/4403.png
    - assets/item_imgs/4402.png
    - assets/item_imgs/4401.png
    - assets/item_imgs/4302.png
    - assets/item_imgs/4301.png
    - assets/item_imgs/4204.png
    - assets/item_imgs/4203.png
    - assets/item_imgs/4202.png
    - assets/item_imgs/4201.png
    - assets/item_imgs/4105.png
    - assets/item_imgs/4104.png
    - assets/item_imgs/4103.png
    - assets/item_imgs/4102.png
    - assets/item_imgs/4101.png
    - assets/item_imgs/4004.png
    - assets/item_imgs/4003.png
    - assets/item_imgs/4001.png
    - assets/item_imgs/3916.png
    - assets/item_imgs/3907.png
    - assets/item_imgs/3905.png
    - assets/item_imgs/3903.png
    - assets/item_imgs/3902.png
    - assets/item_imgs/3901.png
    - assets/item_imgs/3814.png
    - assets/item_imgs/3813.png
    - assets/item_imgs/3812.png
    - assets/item_imgs/3802.png
    - assets/item_imgs/3801.png
    - assets/item_imgs/3800.png
    - assets/item_imgs/3751.png
    - assets/item_imgs/3748.png
    - assets/item_imgs/3742.png
    - assets/item_imgs/3715.png
    - assets/item_imgs/3706.png
    - assets/item_imgs/3695.png
    - assets/item_imgs/3694.png
    - assets/item_imgs/3693.png
    - assets/item_imgs/3692.png
    - assets/item_imgs/3691.png
    - assets/item_imgs/3690.png
    - assets/item_imgs/3683.png
    - assets/item_imgs/3682.png
    - assets/item_imgs/3681.png
    - assets/item_imgs/3680.png
    - assets/item_imgs/3675.png
    - assets/item_imgs/3673.png
    - assets/item_imgs/3672.png
    - assets/item_imgs/3671.png
    - assets/item_imgs/3649.png
    - assets/item_imgs/3648.png
    - assets/item_imgs/3647.png
    - assets/item_imgs/3645.png
    - assets/item_imgs/3643.png
    - assets/item_imgs/3642.png
    - assets/item_imgs/3641.png
    - assets/item_imgs/3640.png
    - assets/item_imgs/3637.png
    - assets/item_imgs/3636.png
    - assets/item_imgs/3635.png
    - assets/item_imgs/3634.png
    - assets/item_imgs/3633.png
    - assets/item_imgs/3631.png
    - assets/item_imgs/3630.png
    - assets/item_imgs/3600.png
    - assets/item_imgs/3599.png
    - assets/item_imgs/3520.png
    - assets/item_imgs/3514.png
    - assets/item_imgs/3513.png
    - assets/item_imgs/3512.png
    - assets/item_imgs/3508.png
    - assets/item_imgs/3504.png
    - assets/item_imgs/3462.png
    - assets/item_imgs/3461.png
    - assets/item_imgs/3460.png
    - assets/item_imgs/3455.png
    - assets/item_imgs/3422.png
    - assets/item_imgs/3416.png
    - assets/item_imgs/3410.png
    - assets/item_imgs/3401.png
    - assets/item_imgs/3400.png
    - assets/item_imgs/3390.png
    - assets/item_imgs/3389.png
    - assets/item_imgs/3388.png
    - assets/item_imgs/3387.png
    - assets/item_imgs/3386.png
    - assets/item_imgs/3385.png
    - assets/item_imgs/3384.png
    - assets/item_imgs/3383.png
    - assets/item_imgs/3382.png
    - assets/item_imgs/3380.png
    - assets/item_imgs/3379.png
    - assets/item_imgs/3374.png
    - assets/item_imgs/3373.png
    - assets/item_imgs/3371.png
    - assets/item_imgs/3364.png
    - assets/item_imgs/3363.png
    - assets/item_imgs/3362.png
    - assets/item_imgs/3361.png
    - assets/item_imgs/3348.png
    - assets/item_imgs/3345.png
    - assets/item_imgs/3340.png
    - assets/item_imgs/3312.png
    - assets/item_imgs/3311.png
    - assets/item_imgs/3310.png
    - assets/item_imgs/3309.png
    - assets/item_imgs/3308.png
    - assets/item_imgs/3307.png
    - assets/item_imgs/3306.png
    - assets/item_imgs/3305.png
    - assets/item_imgs/3304.png
    - assets/item_imgs/3303.png
    - assets/item_imgs/3302.png
    - assets/item_imgs/3301.png
    - assets/item_imgs/3285.png
    - assets/item_imgs/3231.png
    - assets/item_imgs/3230.png
    - assets/item_imgs/3222.png
    - assets/item_imgs/3211.png
    - assets/item_imgs/3200.png
    - assets/item_imgs/3198.png
    - assets/item_imgs/3197.png
    - assets/item_imgs/3196.png
    - assets/item_imgs/3194.png
    - assets/item_imgs/3193.png
    - assets/item_imgs/3191.png
    - assets/item_imgs/3190.png
    - assets/item_imgs/3187.png
    - assets/item_imgs/3185.png
    - assets/item_imgs/3184.png
    - assets/item_imgs/3181.png
    - assets/item_imgs/3175.png
    - assets/item_imgs/3174.png
    - assets/item_imgs/3173.png
    - assets/item_imgs/3172.png
    - assets/item_imgs/3170.png
    - assets/item_imgs/3165.png
    - assets/item_imgs/3163.png
    - assets/item_imgs/3162.png
    - assets/item_imgs/3161.png
    - assets/item_imgs/3158.png
    - assets/item_imgs/3157.png
    - assets/item_imgs/3156.png
    - assets/item_imgs/3155.png
    - assets/item_imgs/3153.png
    - assets/item_imgs/3152.png
    - assets/item_imgs/3151.png
    - assets/item_imgs/3149.png
    - assets/item_imgs/3148.png
    - assets/item_imgs/3147.png
    - assets/item_imgs/3146.png
    - assets/item_imgs/3145.png
    - assets/item_imgs/3144.png
    - assets/item_imgs/3143.png
    - assets/item_imgs/3142.png
    - assets/item_imgs/3140.png
    - assets/item_imgs/3139.png
    - assets/item_imgs/3137.png
    - assets/item_imgs/3136.png
    - assets/item_imgs/3135.png
    - assets/item_imgs/3134.png
    - assets/item_imgs/3133.png
    - assets/item_imgs/3131.png
    - assets/item_imgs/3128.png
    - assets/item_imgs/3124.png
    - assets/item_imgs/3123.png
    - assets/item_imgs/3122.png
    - assets/item_imgs/3118.png
    - assets/item_imgs/3117.png
    - assets/item_imgs/3116.png
    - assets/item_imgs/3115.png
    - assets/item_imgs/3114.png
    - assets/item_imgs/3113.png
    - assets/item_imgs/3112.png
    - assets/item_imgs/3111.png
    - assets/item_imgs/3110.png
    - assets/item_imgs/3109.png
    - assets/item_imgs/3108.png
    - assets/item_imgs/3107.png
    - assets/item_imgs/3105.png
    - assets/item_imgs/3104.png
    - assets/item_imgs/3102.png
    - assets/item_imgs/3101.png
    - assets/item_imgs/3100.png
    - assets/item_imgs/3098.png
    - assets/item_imgs/3097.png
    - assets/item_imgs/3096.png
    - assets/item_imgs/3095.png
    - assets/item_imgs/3094.png
    - assets/item_imgs/3092.png
    - assets/item_imgs/3091.png
    - assets/item_imgs/3090.png
    - assets/item_imgs/3089.png
    - assets/item_imgs/3087.png
    - assets/item_imgs/3086.png
    - assets/item_imgs/3085.png
    - assets/item_imgs/3084.png
    - assets/item_imgs/3083.png
    - assets/item_imgs/3082.png
    - assets/item_imgs/3080.png
    - assets/item_imgs/3078.png
    - assets/item_imgs/3077.png
    - assets/item_imgs/3076.png
    - assets/item_imgs/3075.png
    - assets/item_imgs/3074.png
    - assets/item_imgs/3073.png
    - assets/item_imgs/3072.png
    - assets/item_imgs/3071.png
    - assets/item_imgs/3070.png
    - assets/item_imgs/3069.png
    - assets/item_imgs/3068.png
    - assets/item_imgs/3067.png
    - assets/item_imgs/3065.png
    - assets/item_imgs/3057.png
    - assets/item_imgs/3056.png
    - assets/item_imgs/3053.png
    - assets/item_imgs/3052.png
    - assets/item_imgs/3050.png
    - assets/item_imgs/3048.png
    - assets/item_imgs/3047.png
    - assets/item_imgs/3046.png
    - assets/item_imgs/3044.png
    - assets/item_imgs/3043.png
    - assets/item_imgs/3042.png
    - assets/item_imgs/3041.png
    - assets/item_imgs/3040.png
    - assets/item_imgs/3036.png
    - assets/item_imgs/3035.png
    - assets/item_imgs/3033.png
    - assets/item_imgs/3031.png
    - assets/item_imgs/3030.png
    - assets/item_imgs/3029.png
    - assets/item_imgs/3028.png
    - assets/item_imgs/3027.png
    - assets/item_imgs/3026.png
    - assets/item_imgs/3025.png
    - assets/item_imgs/3024.png
    - assets/item_imgs/3022.png
    - assets/item_imgs/3020.png
    - assets/item_imgs/3010.png
    - assets/item_imgs/3009.png
    - assets/item_imgs/3008.png
    - assets/item_imgs/3007.png
    - assets/item_imgs/3006.png
    - assets/item_imgs/3005.png
    - assets/item_imgs/3004.png
    - assets/item_imgs/3003.png
    - assets/item_imgs/3001.png
    - assets/item_imgs/2424.png
    - assets/item_imgs/2423.png
    - assets/item_imgs/2422.png
    - assets/item_imgs/2421.png
    - assets/item_imgs/2420.png
    - assets/item_imgs/2419.png
    - assets/item_imgs/2403.png
    - assets/item_imgs/2319.png
    - assets/item_imgs/2140.png
    - assets/item_imgs/2139.png
    - assets/item_imgs/2138.png
    - assets/item_imgs/2065.png
    - assets/item_imgs/2062.png
    - assets/item_imgs/2061.png
    - assets/item_imgs/2060.png
    - assets/item_imgs/2059.png
    - assets/item_imgs/2058.png
    - assets/item_imgs/2057.png
    - assets/item_imgs/2056.png
    - assets/item_imgs/2055.png
    - assets/item_imgs/2054.png
    - assets/item_imgs/2053.png
    - assets/item_imgs/2052.png
    - assets/item_imgs/2051.png
    - assets/item_imgs/2050.png
    - assets/item_imgs/2047.png
    - assets/item_imgs/2033.png
    - assets/item_imgs/2032.png
    - assets/item_imgs/2031.png
    - assets/item_imgs/2015.png
    - assets/item_imgs/2013.png
    - assets/item_imgs/2012.png
    - assets/item_imgs/2011.png
    - assets/item_imgs/2010.png
    - assets/item_imgs/2009.png
    - assets/item_imgs/2004.png
    - assets/item_imgs/2003.png
    - assets/item_imgs/1419.png
    - assets/item_imgs/1416.png
    - assets/item_imgs/1414.png
    - assets/item_imgs/1413.png
    - assets/item_imgs/1412.png
    - assets/item_imgs/1402.png
    - assets/item_imgs/1401.png
    - assets/item_imgs/1400.png
    - assets/item_imgs/1083.png
    - assets/item_imgs/1082.png
    - assets/item_imgs/1059.png
    - assets/item_imgs/1058.png
    - assets/item_imgs/1057.png
    - assets/item_imgs/1056.png
    - assets/item_imgs/1055.png
    - assets/item_imgs/1054.png
    - assets/item_imgs/1053.png
    - assets/item_imgs/1052.png
    - assets/item_imgs/1051.png
    - assets/item_imgs/1043.png
    - assets/item_imgs/1042.png
    - assets/item_imgs/1041.png
    - assets/item_imgs/1039.png
    - assets/item_imgs/1038.png
    - assets/item_imgs/1037.png
    - assets/item_imgs/1036.png
    - assets/item_imgs/1033.png
    - assets/item_imgs/1031.png
    - assets/item_imgs/1029.png
    - assets/item_imgs/1028.png
    - assets/item_imgs/1027.png
    - assets/item_imgs/1026.png
    - assets/item_imgs/1018.png
    - assets/item_imgs/1011.png
    - assets/item_imgs/1006.png
    - assets/item_imgs/1004.png
    - assets/item_imgs/1001.png