name: LeagueAI
version: 2.0.1
description: League AI is the \#1 League of Legends build recommendation AI
homepage: http://leagueai.gg/

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.16.1-pre.24'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
  firebase_database: ^3.1.6
  cloud_functions: ^0.4.2+3
  firebase_auth: ^0.16.0
#  firebase_messaging: ^6.0.13
  intl: ^0.16.1
  firebase_admob: ^0.9.3+2
  flutter_launcher_icons: ^0.8.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  qr_flutter: ^3.2.0
  qrcode_reader: ^0.4.4
  watcher: ^0.9.7+14
  wakelock: ^0.1.3+4
  notification_permissions: ^0.4.4
  permission_handler: ^5.0.0+hotfix.5
  apple_sign_in: ^0.1.0
  video_player: ^1.0.0
  # btnonce:
  #   path: ./plugins/btnonce
  fbfunctions:
    path: ./plugins/fbfunctions
  launchbrowser:
    path: ./plugins/launchbrowser


  flutter_firebase_ui:
      path: flutter_firebase_ui

flutter_icons:
  image_path: "assets/icons/logo_new_black_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/logo_new_black_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: Rubik
        fonts:
          - asset: assets/fonts/Rubik-Regular.ttf
          - asset: assets/fonts/Rubik-Medium.ttf
            weight: 500
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 300
          - asset: assets/fonts/Roboto-Black.ttf
            weight: 600
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Light.ttf
            weight: 200
          - asset: assets/fonts/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Rubik-Medium.ttf
            weight: 400

  uses-material-design: true
  assets:
    #videos
    - assets/video/final_openshot_export_handbrake.mp4

    #json
    - assets/data/item2id.json
    - assets/data/champ2id.json

    #icons
#    - assets/icons/logo_head_only.png
#    - assets/icons/logo_head_small.png
    - assets/icons/logo_new.png

    #imgs
    - assets/imgs/1.png
    - assets/imgs/ai.gif
    - assets/imgs/brain2.png

#item imgs

    - assets/train_imgs/0.png
    - assets/train_imgs/1001.png
    - assets/train_imgs/1004.png
    - assets/train_imgs/1006.png
    - assets/train_imgs/1011.png
    - assets/train_imgs/1018.png
    - assets/train_imgs/1026.png
    - assets/train_imgs/1027.png
    - assets/train_imgs/1028.png
    - assets/train_imgs/1029.png
    - assets/train_imgs/1031.png
    - assets/train_imgs/1033.png
    - assets/train_imgs/1036.png
    - assets/train_imgs/1037.png
    - assets/train_imgs/1038.png
    - assets/train_imgs/1042.png
    - assets/train_imgs/1043.png
    - assets/train_imgs/1052.png
    - assets/train_imgs/1053.png
    - assets/train_imgs/1054.png
    - assets/train_imgs/1055.png
    - assets/train_imgs/1056.png
    - assets/train_imgs/1057.png
    - assets/train_imgs/1058.png
    - assets/train_imgs/1082.png
    - assets/train_imgs/1083.png
    - assets/train_imgs/2003.png
    - assets/train_imgs/2004.png
    - assets/train_imgs/2009.png
    - assets/train_imgs/2010.png
    - assets/train_imgs/2013.png
    - assets/train_imgs/2011.png
    - assets/train_imgs/2015.png
    - assets/train_imgs/2031.png
    - assets/train_imgs/2033.png
    - assets/train_imgs/2055.png
    - assets/train_imgs/2056.png
    - assets/train_imgs/2057.png
    - assets/train_imgs/2058.png
    - assets/train_imgs/2059.png
    - assets/train_imgs/2060.png
    - assets/train_imgs/2061.png
    - assets/train_imgs/2062.png
    - assets/train_imgs/2138.png
    - assets/train_imgs/2139.png
    - assets/train_imgs/2140.png
    - assets/train_imgs/2319.png
    - assets/train_imgs/2403.png
    - assets/train_imgs/2422.png
    - assets/train_imgs/2420.png
    - assets/train_imgs/2419.png
    - assets/train_imgs/2421.png
    - assets/train_imgs/2423.png
    - assets/train_imgs/2424.png
    - assets/train_imgs/3001.png
    - assets/train_imgs/3003.png
    - assets/train_imgs/3004.png
    - assets/train_imgs/3006.png
    - assets/train_imgs/3009.png
    - assets/train_imgs/3020.png
    - assets/train_imgs/3024.png
    - assets/train_imgs/3026.png
    - assets/train_imgs/3031.png
    - assets/train_imgs/3033.png
    - assets/train_imgs/3035.png
    - assets/train_imgs/3036.png
    - assets/train_imgs/3040.png
    - assets/train_imgs/3041.png
    - assets/train_imgs/3042.png
    - assets/train_imgs/3044.png
    - assets/train_imgs/3046.png
    - assets/train_imgs/3047.png
    - assets/train_imgs/3050.png
    - assets/train_imgs/3053.png
    - assets/train_imgs/3057.png
    - assets/train_imgs/3065.png
    - assets/train_imgs/3067.png
    - assets/train_imgs/3070.png
    - assets/train_imgs/3071.png
    - assets/train_imgs/3072.png
    - assets/train_imgs/3074.png
    - assets/train_imgs/3075.png
    - assets/train_imgs/3076.png
    - assets/train_imgs/3077.png
    - assets/train_imgs/3078.png
    - assets/train_imgs/3082.png
    - assets/train_imgs/3083.png
    - assets/train_imgs/3085.png
    - assets/train_imgs/3086.png
    - assets/train_imgs/3089.png
    - assets/train_imgs/3091.png
    - assets/train_imgs/3094.png
    - assets/train_imgs/3095.png
    - assets/train_imgs/3100.png
    - assets/train_imgs/3101.png
    - assets/train_imgs/3102.png
    - assets/train_imgs/3105.png
    - assets/train_imgs/3107.png
    - assets/train_imgs/3108.png
    - assets/train_imgs/3109.png
    - assets/train_imgs/3110.png
    - assets/train_imgs/3111.png
    - assets/train_imgs/3113.png
    - assets/train_imgs/3114.png
    - assets/train_imgs/3115.png
    - assets/train_imgs/3116.png
    - assets/train_imgs/3117.png
    - assets/train_imgs/3123.png
    - assets/train_imgs/3124.png
    - assets/train_imgs/3133.png
    - assets/train_imgs/3134.png
    - assets/train_imgs/3135.png
    - assets/train_imgs/3136.png
    - assets/train_imgs/3139.png
    - assets/train_imgs/3140.png
    - assets/train_imgs/3142.png
    - assets/train_imgs/3143.png
    - assets/train_imgs/3153.png
    - assets/train_imgs/3155.png
    - assets/train_imgs/3156.png
    - assets/train_imgs/3157.png
    - assets/train_imgs/3158.png
    - assets/train_imgs/3165.png
    - assets/train_imgs/3190.png
    - assets/train_imgs/3191.png
    - assets/train_imgs/3193.png
    - assets/train_imgs/3196.png
    - assets/train_imgs/3197.png
    - assets/train_imgs/3198.png
    - assets/train_imgs/3200.png
    - assets/train_imgs/3211.png
    - assets/train_imgs/3222.png
    - assets/train_imgs/3330.png
    - assets/train_imgs/3340.png
    - assets/train_imgs/3363.png
    - assets/train_imgs/3364.png
    - assets/train_imgs/3371.png
    - assets/train_imgs/3373.png
    - assets/train_imgs/3374.png
    - assets/train_imgs/3379.png
    - assets/train_imgs/3380.png
    - assets/train_imgs/3382.png
    - assets/train_imgs/3383.png
    - assets/train_imgs/3384.png
    - assets/train_imgs/3386.png
    - assets/train_imgs/3387.png
    - assets/train_imgs/3388.png
    - assets/train_imgs/3389.png
    - assets/train_imgs/3390.png
    - assets/train_imgs/3400.png
    - assets/train_imgs/3504.png
    - assets/train_imgs/3508.png
    - assets/train_imgs/3513.png
    - assets/train_imgs/3599.png
    - assets/train_imgs/3600.png
    - assets/train_imgs/3742.png
    - assets/train_imgs/3748.png
    - assets/train_imgs/6660.png
    - assets/train_imgs/3801.png
    - assets/train_imgs/3802.png
    - assets/train_imgs/6333.png
    - assets/train_imgs/3814.png
    - assets/train_imgs/3901.png
    - assets/train_imgs/3902.png
    - assets/train_imgs/3903.png
    - assets/train_imgs/3916.png
    - assets/train_imgs/3179.png
    - assets/train_imgs/3181.png
    - assets/train_imgs/3850.png
    - assets/train_imgs/3851.png
    - assets/train_imgs/3853.png
    - assets/train_imgs/3862.png
    - assets/train_imgs/3863.png
    - assets/train_imgs/3864.png
    - assets/train_imgs/3858.png
    - assets/train_imgs/3859.png
    - assets/train_imgs/3860.png
    - assets/train_imgs/3854.png
    - assets/train_imgs/3855.png
    - assets/train_imgs/3857.png
    - assets/train_imgs/6671.png
    - assets/train_imgs/6672.png
    - assets/train_imgs/6673.png
    - assets/train_imgs/3068.png
    - assets/train_imgs/6662.png
    - assets/train_imgs/6664.png
    - assets/train_imgs/6691.png
    - assets/train_imgs/6692.png
    - assets/train_imgs/6693.png
    - assets/train_imgs/6653.png
    - assets/train_imgs/6655.png
    - assets/train_imgs/6656.png
    - assets/train_imgs/3152.png
    - assets/train_imgs/4633.png
    - assets/train_imgs/4636.png
    - assets/train_imgs/6630.png
    - assets/train_imgs/6631.png
    - assets/train_imgs/6632.png
    - assets/train_imgs/2065.png
    - assets/train_imgs/6617.png
    - assets/train_imgs/4005.png
    - assets/train_imgs/6676.png
    - assets/train_imgs/6675.png
    - assets/train_imgs/4401.png
    - assets/train_imgs/6695.png
    - assets/train_imgs/4628.png
    - assets/train_imgs/4629.png
    - assets/train_imgs/4637.png
    - assets/train_imgs/6694.png
    - assets/train_imgs/6035.png
    - assets/train_imgs/6609.png
    - assets/train_imgs/3011.png
    - assets/train_imgs/6616.png
    - assets/train_imgs/4641.png
    - assets/train_imgs/4638.png
    - assets/train_imgs/4643.png
    - assets/train_imgs/1035.png
    - assets/train_imgs/1039.png
    - assets/train_imgs/6670.png
    - assets/train_imgs/6677.png
    - assets/train_imgs/4630.png
    - assets/train_imgs/4635.png
    - assets/train_imgs/3145.png
    - assets/train_imgs/3066.png
    - assets/train_imgs/4632.png
    - assets/train_imgs/3051.png
    - assets/train_imgs/6029.png
    - assets/train_imgs/4642.png
    
    - assets/train_imgs/champs/Aatrox.png
    - assets/train_imgs/champs/Ahri.png
    - assets/train_imgs/champs/Akali.png
    - assets/train_imgs/champs/Alistar.png
    - assets/train_imgs/champs/Amumu.png
    - assets/train_imgs/champs/Anivia.png
    - assets/train_imgs/champs/Annie.png
    - assets/train_imgs/champs/Aphelios.png
    - assets/train_imgs/champs/AscendedKayle.png
    - assets/train_imgs/champs/Ashe.png
    - assets/train_imgs/champs/AurelionSol.png
    - assets/train_imgs/champs/Azir.png
    - assets/train_imgs/champs/Bard.png
    - assets/train_imgs/champs/Blitzcrank.png
    - assets/train_imgs/champs/Brand.png
    - assets/train_imgs/champs/Braum.png
    - assets/train_imgs/champs/Caitlyn.png
    - assets/train_imgs/champs/Camille.png
    - assets/train_imgs/champs/Cassiopeia.png
    - assets/train_imgs/champs/Chogath.png
    - assets/train_imgs/champs/Corki.png
    - assets/train_imgs/champs/Darius.png
    - assets/train_imgs/champs/Diana.png
    - assets/train_imgs/champs/Draven.png
    - assets/train_imgs/champs/DrMundo.png
    - assets/train_imgs/champs/Ekko.png
    - assets/train_imgs/champs/Elise.png
    - assets/train_imgs/champs/Empty.png
    - assets/train_imgs/champs/Evelynn.png
    - assets/train_imgs/champs/Ezreal.png
    - assets/train_imgs/champs/Fiddlesticks.png
    - assets/train_imgs/champs/Fiora.png
    - assets/train_imgs/champs/Fizz.png
    - assets/train_imgs/champs/Galio.png
    - assets/train_imgs/champs/Gangplank.png
    - assets/train_imgs/champs/Garen.png
    - assets/train_imgs/champs/Gnar.png
    - assets/train_imgs/champs/Gragas.png
    - assets/train_imgs/champs/Graves.png
    - assets/train_imgs/champs/Hecarim.png
    - assets/train_imgs/champs/Heimerdinger.png
    - assets/train_imgs/champs/Illaoi.png
    - assets/train_imgs/champs/Irelia.png
    - assets/train_imgs/champs/Ivern.png
    - assets/train_imgs/champs/Janna.png
    - assets/train_imgs/champs/JarvanIV.png
    - assets/train_imgs/champs/Jax.png
    - assets/train_imgs/champs/Jayce.png
    - assets/train_imgs/champs/Jhin.png
    - assets/train_imgs/champs/Jinx.png
    - assets/train_imgs/champs/Kaisa.png
    - assets/train_imgs/champs/Kalista.png
    - assets/train_imgs/champs/Karma.png
    - assets/train_imgs/champs/Karthus.png
    - assets/train_imgs/champs/Kassadin.png
    - assets/train_imgs/champs/Katarina.png
    - assets/train_imgs/champs/Kayle.png
    - assets/train_imgs/champs/Kayn.png
    - assets/train_imgs/champs/Kennen.png
    - assets/train_imgs/champs/Khazix.png
    - assets/train_imgs/champs/Kindred.png
    - assets/train_imgs/champs/Kled.png
    - assets/train_imgs/champs/KogMaw.png
    - assets/train_imgs/champs/Leblanc.png
    - assets/train_imgs/champs/LeeSin.png
    - assets/train_imgs/champs/Leona.png
    - assets/train_imgs/champs/Lillia.png
    - assets/train_imgs/champs/Lissandra.png
    - assets/train_imgs/champs/Lucian.png
    - assets/train_imgs/champs/Lulu.png
    - assets/train_imgs/champs/Lux.png
    - assets/train_imgs/champs/Malphite.png
    - assets/train_imgs/champs/Malzahar.png
    - assets/train_imgs/champs/Maokai.png
    - assets/train_imgs/champs/MasterYi.png
    - assets/train_imgs/champs/MegaGnar.png
    - assets/train_imgs/champs/MissFortune.png
    - assets/train_imgs/champs/MonkeyKing.png
    - assets/train_imgs/champs/Mordekaiser.png
    - assets/train_imgs/champs/Morgana.png
    - assets/train_imgs/champs/Nami.png
    - assets/train_imgs/champs/Nasus.png
    - assets/train_imgs/champs/Nautilus.png
    - assets/train_imgs/champs/Neeko.png
    - assets/train_imgs/champs/Nidalee.png
    - assets/train_imgs/champs/Nocturne.png
    - assets/train_imgs/champs/Nunu.png
    - assets/train_imgs/champs/Olaf.png
    - assets/train_imgs/champs/Orianna.png
    - assets/train_imgs/champs/Ornn.png
    - assets/train_imgs/champs/Pantheon.png
    - assets/train_imgs/champs/Poppy.png
    - assets/train_imgs/champs/Pyke.png
    - assets/train_imgs/champs/Qiyana.png
    - assets/train_imgs/champs/Quinn.png
    - assets/train_imgs/champs/Rakan.png
    - assets/train_imgs/champs/Rammus.png
    - assets/train_imgs/champs/RekSai.png
    - assets/train_imgs/champs/Renekton.png
    - assets/train_imgs/champs/Rengar.png
    - assets/train_imgs/champs/Rhaast.png
    - assets/train_imgs/champs/Riven.png
    - assets/train_imgs/champs/Rumble.png
    - assets/train_imgs/champs/Ryze.png
    - assets/train_imgs/champs/Samira.png
    - assets/train_imgs/champs/Seraphine.png
    - assets/train_imgs/champs/Sejuani.png
    - assets/train_imgs/champs/Senna.png
    - assets/train_imgs/champs/Sett.png
    - assets/train_imgs/champs/Shaco.png
    - assets/train_imgs/champs/ShadowAssassin.png
    - assets/train_imgs/champs/Shen.png
    - assets/train_imgs/champs/Shyvana.png
    - assets/train_imgs/champs/Singed.png
    - assets/train_imgs/champs/Sion.png
    - assets/train_imgs/champs/Sivir.png
    - assets/train_imgs/champs/Skarner.png
    - assets/train_imgs/champs/Sona.png
    - assets/train_imgs/champs/Soraka.png
    - assets/train_imgs/champs/Swain.png
    - assets/train_imgs/champs/Sylas.png
    - assets/train_imgs/champs/Syndra.png
    - assets/train_imgs/champs/TahmKench.png
    - assets/train_imgs/champs/Taliyah.png
    - assets/train_imgs/champs/Talon.png
    - assets/train_imgs/champs/Taric.png
    - assets/train_imgs/champs/Teemo.png
    - assets/train_imgs/champs/Thresh.png
    - assets/train_imgs/champs/Tristana.png
    - assets/train_imgs/champs/Trundle.png
    - assets/train_imgs/champs/Tryndamere.png
    - assets/train_imgs/champs/TwistedFate.png
    - assets/train_imgs/champs/Twitch.png
    - assets/train_imgs/champs/Udyr.png
    - assets/train_imgs/champs/Urgot.png
    - assets/train_imgs/champs/Varus.png
    - assets/train_imgs/champs/Vayne.png
    - assets/train_imgs/champs/Veigar.png
    - assets/train_imgs/champs/Velkoz.png
    - assets/train_imgs/champs/Vi.png
    - assets/train_imgs/champs/Viktor.png
    - assets/train_imgs/champs/Vladimir.png
    - assets/train_imgs/champs/Volibear.png
    - assets/train_imgs/champs/Warwick.png
    - assets/train_imgs/champs/Xayah.png
    - assets/train_imgs/champs/Xerath.png
    - assets/train_imgs/champs/XinZhao.png
    - assets/train_imgs/champs/Yasuo.png
    - assets/train_imgs/champs/Yone.png
    - assets/train_imgs/champs/Yorick.png
    - assets/train_imgs/champs/Yuumi.png
    - assets/train_imgs/champs/Zac.png
    - assets/train_imgs/champs/Zed.png
    - assets/train_imgs/champs/Ziggs.png
    - assets/train_imgs/champs/Zilean.png
    - assets/train_imgs/champs/Zoe.png
    - assets/train_imgs/champs/Zyra.png
